theme: jekyll-theme-minimal 
title: Your Name - Research & Teaching 

name: Luís Pinto-Coelho
position: Your Position
department: Your Department
university: Your University
bio: "A concise and engaging summary of your research interests and teaching experience."
